"""Update video schema

Revision ID: 0f3b61276fd4
Revises: abcdef123456
Create Date: 2026-07-20 19:50:46.969520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3b61276fd4'
down_revision: Union[str, Sequence[str], None] = 'abcdef123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_metadata', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.alter_column('video_metadata', 'safe_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('video_metadata_video_id_fkey'), 'video_metadata', type_='foreignkey')
    op.drop_column('video_metadata', 'video_id')
    op.add_column('videos', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.alter_column('videos', 'safe_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('videos_safe_filename_key'), 'videos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('videos_safe_filename_key'), 'videos', ['safe_filename'], postgresql_nulls_not_distinct=False)
    op.alter_column('videos', 'safe_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('videos', 'batch_id')
    op.add_column('video_metadata', sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('video_metadata_video_id_fkey'), 'video_metadata', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.alter_column('video_metadata', 'safe_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('video_metadata', 'batch_id')
    # ### end Alembic commands ###
