"""Add transform_matrix to PointCloudMetadata

Revision ID: d0f09e01fa6d
Revises: 0f3b61276fd4
Create Date: 2026-07-22 10:37:10.175959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f09e01fa6d'
down_revision: Union[str, Sequence[str], None] = '0f3b61276fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pointclouds', sa.Column('transform_matrix', postgresql.ARRAY(sa.Float()), nullable=False, server_default='{1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pointclouds', 'transform_matrix')
    # ### end Alembic commands ###
