"""Add PointCloudCameraRoute

Revision ID: d60c7c7992f5
Revises: d0f09e01fa6d
Create Date: 2026-07-23 12:08:30.055576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd60c7c7992f5'
down_revision: Union[str, Sequence[str], None] = 'd0f09e01fa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pointcloud_camera_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pointcloud_id', sa.UUID(), nullable=False),
    sa.Column('orig_filename', sa.String(length=255), nullable=False),
    sa.Column('safe_filename', sa.String(length=255), nullable=True),
    sa.Column('number_of_points', sa.Integer(), nullable=False),
    sa.Column('min_x', sa.Float(), nullable=True),
    sa.Column('min_y', sa.Float(), nullable=True),
    sa.Column('min_z', sa.Float(), nullable=True),
    sa.Column('max_x', sa.Float(), nullable=True),
    sa.Column('max_y', sa.Float(), nullable=True),
    sa.Column('max_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pcid', sa.Integer(), nullable=False),
    sa.Column('transform_matrix', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.ForeignKeyConstraint(['pointcloud_id'], ['pointclouds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pointcloud_camera_routes')
    # ### end Alembic commands ###
